#!groovy

import groovy.json.JsonSlurper
import groovy.json.JsonException

node {
    stage('Preparation') {

        //env.staging='{"BACKEND_URL":"backend_host:4000/","FRONTEND_URL":"frontend_host:8080/"}'
        //env.prod='{"BACKEND_URL":"backend_host:4000/","FRONTEND_URL":"frontend_host:8080/"}'
        try {
            (new JsonSlurper()).parseText(env.staging)
            (new JsonSlurper()).parseText(env.prod)
        } catch (JsonException | IllegalArgumentException e) {
             error("Please define the staging and prod environment variables, using the Environment Injector Plugin, as JSON-formatted string, e.g. staging={\"BACKEND_URL\":\"backend_host:4000/\",\"FRONTEND_URL\":\"frontend_host:8080/\"}")
        }

        deleteDir()
        checkout scm
        sh 'git submodule update --init --recursive'
        env.GIT_URL = sh(returnStdout: true, script: 'git config --get remote.origin.url').trim()
        env.GIT_BRANCH = sh(returnStdout: true, script: 'git rev-parse --abbrev-ref HEAD').trim()
        env.GIT_COMMIT = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
        def workspace = pwd()
        sh "cp /var/jenkins_home/deploy-app-vars.yml ${workspace}/ci/ansible/"
        sh "cp /var/jenkins_home/ansible-hosts ${workspace}/ci/ansible/hosts"
        dir ('web-recorder-frontend') {
            withEnv(['NODE_ENV=development']) {
                nodejs(nodeJSInstallationName: 'recent node') {
                    sh 'npm install -g @angular/cli'
                    sh 'npm install'
                    sh 'chmod u+x prebuild.js'
                    sh 'npm run-script prebuild'
                    sh 'ng build --prod --aot --environment=staging'
                }
            }
        }
    }

    dir ('web-recorder-frontend') {
        stage('Test') {
            withEnv(['NODE_ENV=development']) {
                nodejs(nodeJSInstallationName: 'recent node') {
                    //sh 'npm test'
                }
            }
        }

        stage('SonarQube analysis') {
            // The SonarQube server requires at least 2GB of RAM to run efficiently and 1GB of free RAM for the OS.
            def scannerHome = tool 'sonar scanner';
            withSonarQubeEnv('sonar server') {
                sh "${scannerHome}/bin/sonar-scanner -Dproject.settings=sonar-project.properties"
            }
        }

        stage("SonarQube Quality Gate") {
            timeout(time: 1, unit: 'HOURS') {
                def qg = waitForQualityGate()
                if (qg.status != 'OK') {
                    error "Pipeline aborted due to quality gate failure: ${qg.status}"
                }
            }
        }
    }

    stage('Staging deploy') {
        ansiColor('xterm') {
            ansiblePlaybook(
                colorized: true,
                inventory: 'ci/ansible/hosts',
                playbook: 'ci/ansible/deploy-app-staging.yml',
                sudoUser: null,
                extraVars: [
                    "app_port":"8080",
                    "app_subdir":"web-recorder-frontend",
                    "node_environment":env.staging
                ]
            )
        }
    }
}

stage('Production deploy approval') {
    timeout(time: 5, unit: 'DAYS') {
        def deploy = input(id: 'userInput', message: 'Deploy to production?')
    }
}

node {
    stage('Production deploy') {
        sh 'ng build --prod --aot --environment=prod'
        ansiColor('xterm') {
            ansiblePlaybook(
                colorized: true,
                inventory: 'ci/ansible/hosts',
                playbook: 'ci/ansible/deploy-app-production.yml',
                sudoUser: null,
                extraVars: [
                    "app_port":"8080",
                    "app_subdir":"web-recorder-frontend",
                    "node_environment":env.prod
                ]
            )
        }
    }
}
